services: 
  consumer:
    build: 
        context: .
        dockerfile: SimpleConsumerProducer.Consumer/Dockerfile
    ports:
      - "7045:7045"
    depends_on: 
      rabbitmq:
        condition: service_healthy
  producer:
    build: 
        context: .
        dockerfile: SimpleConsumerProducer.Producer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
        rabbitmq:
            condition: service_healthy
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 3